//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentCash.DBModel
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// DateWash
    /// </summary>
    public partial class DateWash
    {
    
        /// <summary>
        /// 
        /// </summary>
        public int DateWashID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string DateStr { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string UserID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string IsFinish { get; set; }
    }
}
