//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPayLog
    {
        public int PersonPayLog_ID { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PaySummary { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUser { get; set; }
        public string CheckStatus { get; set; }
        public Nullable<int> CheckLogID { get; set; }
    }
}
