//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public string asdf23432 { get; set; }
        public string asf { get; set; }
        public string Columnasdf_3 { get; set; }
        public string dfg { get; set; }
        public string asfff { get; set; }
    }
}
